### PR TITLE
added cookie consent and anti adblock

### PR DESCRIPTION
**Pull request by gamfam1**
anti adblock is for revenue
cookie consent is for legal reasons

### CODE REVIEW

**Comment by gamfam1** [comment]
@Thedogecraft

**Comment by gamfam1** [comment]
@Thedogecraft @WavyBacon @M1noa @3kh0

**Comment by 3kh0** [comment]
Nah fuck you, I want my adblock, if the site provides valuable content, I will turn it off. Do not force it off

**Comment by gamfam1** [comment]
> Nah fuck you, I want my adblock, if the site provides valuable content, I will turn it off. Do not force it off

well the site provides games so it is valuable

**Comment by M1noa** [comment]
get there ass

**Comment by 3kh0** [comment]
> > Nah fuck you, I want my adblock, if the site provides valuable content, I will turn it off. Do not force it off
> 
> well the site provides games so it is valuable

It is to the opinion of the actual user. I do not think this site is providing me anything new that I cant find anywhere else. I will leave my adblock on. Plus studies show that preventing adblock just makes people get stronger adblock

**Comment by M1noa** [comment]
meow

**Pull request closed without merging**
