### PR TITLE
added stuff

### PR DESCRIPTION
**Pull request by gamfam1**
bootstrap added for spoofing
pr0x is now search to be less confusing
polyfills added to increase compatibility

### CODE REVIEW

**Comment by gamfam1** [comment]
@Thedogecraft @M1noa

**Review by thedogecraft — CHANGES_REQUESTED** [review]
Whats polyfill for and why bootstrap?

**Comment by gamfam1** [comment]
> Whats polyfill for and why bootstrap?

bootstrap for spoofing and polyfills add extra compatibility to old versions of browsers (most of your users likely use outdated browsers as it is a unblocked site)

**Comment by gamfam1** [comment]
url scanners will think bootstrap was added to the site and it will trick them

**Comment by gamfam1** [comment]
@Thedogecraft can you merge?

**Comment by gamfam1** [comment]
@Thedogecraft

**Pull request closed without merging**
